try:
    print(x)
except:
    print("An Error occurred")
finally:
    print("Success")